[package]
name = "disrecord"
version = "0.2.17"
edition = "2021"

[dependencies]
axum = "0.6.18"
bincode = "1.3.3"
clap = { version = "4.1.8", features = ["derive"] }
env_logger = "0.10.0"
futures = "0.3.28"
humantime = "2.1.0"
itertools = "0.10.5"
log = "0.4.17"
log-panics = "2.1.0"
parse_duration = "2.1.1"
regex = "1.8.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serenity = { version = "0.11.5", default_features = false, features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "voice"] }
songbird = "0.3.1"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["macros", "rt-multi-thread", "sync", "fs", "process"] }
ulid = { version = "1.0.0", features = ["serde"] }
zip = { version = "0.6.4", default_features = false }

[dev-dependencies]
rand = "0.8.5"